name: ESlint

on:
  pull_request:
    types: [opened]

jobs:
  send_message_on_rocket:
    runs-on: ubuntu-latest
    steps:
      - name: ESlint checker
        uses: hallee/eslint-action@master
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
