name: ESlint

on:
  pull_request:
    types: [opened]

jobs:
  send_message_on_rocket:
    runs-on: ubuntu-latest
    steps:
      - name: Travis-CI test check
        uses: travis-ci/actions@master"
        if: always()
        env:
          TRAVIS_TOKEN: ${{ secrets.TRAVIS_TOKEN }}
